---
- hosts: all
  vars:
    admin_email: changeme@example.com
  tasks:
    - name: Install the basics
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - git
        - vim

    - name: Add PHP PPA
      apt_repository: repo=ppa:ondrej/php5

    - name: Install PHP
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - php5-fpm
        - php5-cli

    - name: Install PHP modules
      apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - php5-common
        - php5-mcrypt
        - php5-intl
        - php5-curl
        - php5-dev
        - php5-gd
        - php5-memcached
        - php5-mysql
        - php5-gmp
        - php5-json
        - phpunit

    - name: Enable mcrypt
      command: php5enmod mcrypt

    - name: Restart php5-fpm
      sudo: True
      shell: service php5-fpm restart

    - name: Install composer globally
      shell:  curl -sS https://getcomposer.org/installer | /usr/bin/php && sudo /bin/mv -f composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

    - name: Add source for NodeJS
      shell: 'curl --silent --location https://deb.nodesource.com/setup_5.x | sudo bash -'

    - name: Install NodeJS
      apt: pkg=nodejs state=latest

    - name: Install Gulp globally
      shell: npm install -g gulp

    - name: Install Postfix
      apt: pkg=postfix state=latest

    - name: Install memcached
      apt: name=memcached state=latest

    - name: Install MySQL
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - mysql-client

    - name: Create database
      shell: mysql -u root < db-setup.sql
      args:
        chdir: /srv/ork
        creates: db_created

    - name: Import database structure
      shell: mysql -u root -D ork < ork.sql
      args:
        chdir: /srv/ork
        creates: db_migrated

    - name: Create admin setup SQL file
      template:
        src: admin-setup.sql.j2
        dest: /srv/ork/admin-setup.sql

    - name: Run admin setup
      shell: mysql -u root -D ork < admin-setup.sql
      args:
        chdir: /srv/ork
        creates: admin_created

    - name: Place config file
      template:
        src: config.php.j2
        dest: /srv/ork/config.php

    - name: Add nginx PPA
      apt_repository: repo=ppa:nginx/development

    - name: Install nginx
      apt: name=nginx state=latest update_cache=yes

    - name: Remove the nginx example configuration files
      file:
        path: /etc/nginx/{{ item }}
        state: absent
      with_items:
        - sites-available/default
        - sites-enabled/default
        - conf.d/default.conf
        - conf.d/example_ssl.conf

    - name: Add nginx virtualhost config
      template:
        src: nginx-vhost
        dest: /etc/nginx/sites-available/ork

    - name: Enable nginx virtualhost
      file:
        src: /etc/nginx/sites-available/ork
        dest: /etc/nginx/sites-enabled/ork
        state: link

    - name: Add php.conf nginx config file
      template:
        src: php.conf
        dest: /etc/nginx/php.conf

    - name: Restart nginx
      command: service nginx restart

    - name: Start the memcached service
      service: name=memcached state=started enabled=yes

    - name: Restart the Postfix service
      service: name=postfix state=restarted enabled=yes